FROM python:3.6                      
LABEL maintainer itqs                
ENV PYTHONUNBUFFERED 1                 
WORKDIR /itqs
COPY requirements.txt /itqs/            
RUN pip install -r requirements.txt    